name: 'build and deploy Speckle functions'
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-automate-function-version:
    env:
      FUNCTION_SCHEMA_FILE_NAME: functionSchema.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Debug secrets availability
      - name: Debug secrets availability
        run: |
          echo "Checking secret availability..."
          if [ -n "${{ secrets.SPECKLE_FUNCTION_TOKEN }}" ]; then
            echo "✅ SPECKLE_FUNCTION_TOKEN is available"
          else
            echo "❌ SPECKLE_FUNCTION_TOKEN is missing"
          fi
          if [ -n "${{ secrets.SPECKLE_FUNCTION_ID }}" ]; then
            echo "✅ SPECKLE_FUNCTION_ID is available"
          else
            echo "❌ SPECKLE_FUNCTION_ID is missing"
          fi

      # Validate required secrets exist
      - name: Validate secrets
        run: |
          MISSING_SECRETS=""
          
          if [ -z "${{ secrets.SPECKLE_FUNCTION_TOKEN }}" ]; then
            echo "❌ ERROR: SPECKLE_FUNCTION_TOKEN secret is required"
            MISSING_SECRETS="SPECKLE_FUNCTION_TOKEN "
          fi
          
          if [ -z "${{ secrets.SPECKLE_FUNCTION_ID }}" ]; then
            echo "❌ ERROR: SPECKLE_FUNCTION_ID secret is required"
            MISSING_SECRETS="${MISSING_SECRETS}SPECKLE_FUNCTION_ID "
          fi
          
          if [ -n "$MISSING_SECRETS" ]; then
            echo "Missing secrets: $MISSING_SECRETS"
            echo "Please add these secrets in Settings > Secrets and variables > Actions"
            exit 1
          fi
          
          echo "✅ All required secrets are present"
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install specklepy==2.21.4
          pip install pytest==7.4.2
          pip install black==23.3.0
          pip install ruff==0.0.271
          pip install mypy==1.3.0
          pip install pydantic-settings==2.3.0
          echo "✅ Core dependencies installed successfully"
          
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            python -m pytest tests/ -v
          else
            echo "No tests directory found, skipping tests"
          fi
        continue-on-error: true

      - name: Run code formatting check
        run: |
          python -m black --check .
        continue-on-error: true
          
      - name: Extract functionInputSchema
        id: extract_schema
        run: |
          echo "Generating function schema..."
          python main.py generate_schema ${{ env.FUNCTION_SCHEMA_FILE_NAME }}
          if [ -f "${{ env.FUNCTION_SCHEMA_FILE_NAME }}" ]; then
            echo "✅ Schema file generated successfully"
          else
            echo "❌ Schema file not found"
            exit 1
          fi
          
      # Use the exact configuration from the official example
      - name: Speckle Automate Function - Build and Publish
        uses: specklesystems/speckle-automate-github-composite-action@0.8.1
        with:
          speckle_automate_url: ${{ vars.SPECKLE_AUTOMATE_URL || 'https://automate.speckle.dev' }}
          speckle_token: ${{ secrets.SPECKLE_FUNCTION_TOKEN }}
          speckle_function_id: ${{ secrets.SPECKLE_FUNCTION_ID }}
          speckle_function_input_schema_file_path: ${{ env.FUNCTION_SCHEMA_FILE_NAME }}
          speckle_function_command: 'python -u main.py run'